# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Baseball-Angel-chaiyuting"

# 网页的标题
title: "柴雨婷小站"
# 网站的主标题
name: "柴雨婷的陪伴小札"
# 网站副标题
description: "Accompany & Record my life"

# 分页配置
# 每页文章数量
paginate: 9

# 其它配置, 可忽略, 无需修改
permalink: /:title/
paginate_path: /page:num/
plugins:
  - jekyll-paginate

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
lazyimages: "disabled"
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
